name: Github Actions Example

on:
  pull_request:
  push:
    branches: 
      - master
      - develop

jobs:
  test:
    name: Running Units Tests
    runs-on: windows-latest

    steps:
   
    - name: Install
      run: npm install
    - name: Test
      run: npm test
