on:
  push
jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - run: npm --install
      - run: npm --version
      - uses: actions/checkout@v3
      - run: npm install
      - run: node app.js
